#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -e

uname=`uname`
platform="unknown"
if [ $uname == "Darwin" ]; then
  platform="macos"
elif [ $uname == "Linux" ]; then
  platform="linux"
fi

if [ $platform == "macos" ]; then
  ./setup-homebrew
  ./setup-mac
  ./iterm/setup-iterm
fi

./setup-git
./setup-bash
./setup-node
./setup-go
./setup-ruby
