#!/bin/sh

set -e

source utility

homebrew_prefix="/usr/local"

if [ -d "$homebrew_prefix" ]; then
  if ! [ -r "$homebrew_prefix" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$homebrew_prefix"
  sudo chflags norestricted "$homebrew_prefix"
  sudo chown -R "$LOGNAME:admin" "$homebrew_prefix"
fi

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
  curl -fsS \
    'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
fi

fancy_echo "Updating Homebrew formulae ..."
brew update

apps=(
  coreutils
  docker
  docker-machine
  git
  go
  htop
  plantuml
  telnet
  tree
  vim
  watch
  wget
)

for app in "${apps[@]}"
do
  if brew ls --versions "$app" > /dev/null; then
    fancy_echo "$app installed"
  else
    echo "$app is not installed"
    brew install "$app"
  fi
done

appsCask=(
  "caffeine"
  "iterm2"
  "the-unarchiver"
  "visual-studio-code"
  "google-chrome"
  "itsycal"
  "postman"
  "postgresql"
  "lastpass"
  "skitch"
  "slack"
  "rectangle"
  "spotify"
  "vlc"
  "virtualbox"
  "whatsapp"
)

for appCask in "${appsCask[@]}"
do
  if ! brew cask info "$appCask" > /dev/null; then
    fancy_echo "$appCask installed"
  else
    echo "$appCask is not installed"
    brew cask install "$appCask"
  fi
done
