# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="spaceship"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Disable share history between sessions
unsetopt share_history

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions ssh-agent minikube kubectl)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8


# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

. $HOME/.aliases

. $HOME/z.sh

export EDITOR=nvim

## GOLANG
export GOPATH=$HOME/go
export GOROOT=/opt/homebrew/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

## PYTHON
export PATH=$PATH:$HOME/Library/Python/2.7/bin

## Rust
export PATH="$HOME/.cargo/bin:$PATH"

## GitHub (token loaded from ~/.secrets)

## kubernetes
mkdir -p "$HOME/.kube"
KUBECONFIG="$HOME/.kube/config"

for f in `ls ~/.kube/ | grep kubeconfig`
do
    export KUBECONFIG="$HOME/.kube/$f:$KUBECONFIG";
done

export USE_GKE_GCLOUD_AUTH_PLUGIN=True


##### NVM AUTO USE #####

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

autoload -U add-zsh-hook

nvm_auto_use() {
  if [ -f .nvmrc ]; then
    local nvmrc_node_version=$(<.nvmrc)
    if [ "$(nvm version)" != "v$nvmrc_node_version" ]; then
      nvm use &>/dev/null || {
        echo "Installing Node.js version from .nvmrc: $nvmrc_node_version"
        nvm install "$nvmrc_node_version"
      }
    fi
  fi
}

add-zsh-hook chpwd nvm_auto_use
nvm_auto_use

##### NVM AUTO USE #####

# Spaceship Zsh-theme
SPACESHIP_KUBECTL_CONTEXT_SHOW=false
SPACESHIP_PACKAGE_SHOW=false
SPACESHIP_DOCKER_SHOW=false
SPACESHIP_GIT_STATUS_SHOW=false

# Load secrets from a separate file (not in version control)
[ -f ~/.secrets ] && source ~/.secrets

export PATH=$HOME/.local/bin:$PATH

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/arianbessonart/software/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/arianbessonart/software/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/arianbessonart/software/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/arianbessonart/software/google-cloud-sdk/completion.zsh.inc'; fi

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export PUBLIC_IP=`dig +short @resolver1.opendns.com myip.opendns.com`

eval "$(direnv hook zsh)"

function cursor {
  open -a "/Applications/Cursor.app" "$@"
}

function idea {
  open -a "/Applications/IntelliJ IDEA.app" "$@"
}

# . "$HOME/.local/bin/env"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
export PATH="$HOME/.local/bin:$PATH"

# Added by Antigravity
export PATH="/Users/arianbessonart/.antigravity/antigravity/bin:$PATH"
